export async function up(sql) {
  await sql`
  CREATE TABLE courses (
id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
planet VARCHAR(40) NOT NULL,
price VARCHAR(40) NOT NULL,
description VARCHAR(240) NOT NULL
)
`;
}

export async function down(sql) {
  await sql`
  DROP TABLE courses
  `;
}